version: '3'

services:
  kafka:
    image: spotify/kafka

  ota-ce-db:
    image: mariadb:10.3.14
    command: --max_connections=200
    env_file:
      - ./.secrets
    volumes:
      - ./data/ota-ce-db:/var/lib/mysql
      - ./ota-ce-initialize.sql:/docker-entrypoint-initdb.d/ota-ce-initialize.sql

  treehub:
    image: advancedtelematic/treehub:0.1.27-20-g953fd9b
    user: root
    env_file:
      - ./.secrets
    environment:
      AUTH_PROTOCOL: none
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/treehub
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
      TREEHUB_LOCAL_STORE_PATH: "/treehub-objects"
      TREEHUB_STORAGE: local
    volumes:
      - ./data/treehub-objects:/treehub-objects/object-storage
      - ./wait-for:/wait-for
      - ./treehub-run.sh:/run.sh
    command: "/wait-for ota-ce-db:3306 -- /run.sh"
    entrypoint: ""
    depends_on:
      - ota-ce-db
      - kafka

  tuf-keyserver-daemon:
    image: doanac/tuf-keyserver:0.6.0-19-ge074093
    env_file:
      - ./.secrets
    environment:
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/tuf_keyserver
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
    volumes:
      - ./wait-for:/wait-for
    command: "/wait-for ota-ce-db:3306 -- /opt/keyserver/bin/keyserver -DrootLevel=warn -main com.advancedtelematic.tuf.keyserver.daemon.KeyGenerationDaemon"
    entrypoint: ""
    depends_on:
      - ota-ce-db
      - kafka

  tuf-keyserver:
    image: doanac/tuf-keyserver:0.6.0-19-ge074093
    env_file:
      - ./.secrets
    environment:
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/tuf_keyserver
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
    volumes:
      - ./wait-for:/wait-for
    command: "/wait-for ota-ce-db:3306 -- /opt/keyserver/bin/keyserver -main com.advancedtelematic.tuf.keyserver.Boot"
    entrypoint: ""
    depends_on:
      - ota-ce-db
      - kafka

  tuf-reposerver:
    image: doanac/tuf-reposerver:0.6.0-19-ge074093
    user: root
    env_file:
      - ./.secrets
    environment:
      AUTH_PROTOCOL: none
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/tuf_reposerver
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
      LOCAL_STORAGE_ROOT: /tuf-targets
      STORAGE_TYPE: local
      TUF_KEYSERVER_HOST: tuf-keyserver
      TUF_KEYSERVER_PORT: "9001"
      TUF_REPOSERVER_SIZE_LIMIT: "536870912"
    volumes:
      - ./wait-for:/wait-for
      - ./data/tuf-targets:/tuf-targets

    command: "/wait-for ota-ce-db:3306 -- /opt/reposerver/bin/reposerver"
    entrypoint: ""
    depends_on:
      - ota-ce-db
      - kafka

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${API_PORT-8080}:80
    depends_on:
      - treehub
      - tuf-reposerver
