version: '3'

services:
  director-daemon:
    image: advancedtelematic/director:0.7.0-7-g8cbbcc3
    env_file:
      - ./.secrets
    environment:
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/director
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
      TUF_KEYSERVER_HOST: tuf-keyserver
      TUF_KEYSERVER_PORT: "9001"
      TUF_REPOSERVER_HOST: tuf-reposerver
      TUF_REPOSERVER_PORT: "9001"
    volumes:
      - ./wait-for:/wait-for
    command: "/wait-for ota-ce-db:3306 -- /opt/director/bin/daemon-boot -DrootLevel=warn"
    entrypoint: ""
    depends_on:
      - ota-ce-db
      - tuf-keyserver

  director:
    image: advancedtelematic/director:0.7.0-7-g8cbbcc3
    env_file:
      - ./.secrets
    environment:
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/director
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
      TUF_KEYSERVER_HOST: tuf-keyserver
      TUF_KEYSERVER_PORT: "9001"
      TUF_REPOSERVER_HOST: tuf-reposerver
      TUF_REPOSERVER_PORT: "9001"
    volumes:
      - ./wait-for:/wait-for
    command: "/wait-for ota-ce-db:3306 -- /opt/director/bin/director"
    entrypoint: ""
    depends_on:
      - ota-ce-db
      - director-daemon

  device-registry:
    image: advancedtelematic/device-registry:0.3.0-12-ga1ea92b
    env_file:
      - ./.secrets
    environment:
      AUDITOR_MIGRATE: 'false'
      AUTH_PROTOCOL: none
      BIND_HOST: '0.0.0.0'
      BIND_PORT: '9001'
      DB_URL: jdbc:mariadb://ota-ce-db:3306/device-registry
      KAFKA_HOST: kafka:9092
      REPORT_METRICS: "false"
    volumes:
      - ./wait-for:/wait-for
    command: "/wait-for ota-ce-db:3306 -- /opt/docker/bin/device-registry"
    entrypoint: ""
    depends_on:
      - ota-ce-db

  gateway:
    image: nginx
    volumes:
      - ./uptane-nginx.conf:/etc/nginx/conf.d/default.conf
      - ${CREDS_DATA-./creds-data}/server_keys/server.chain.pem:/server_keys/server.chain.pem:ro
      - ${CREDS_DATA-./creds-data}/server_keys/server.key:/server_keys/server.key:ro
      - ${CREDS_DATA-./creds-data}/server_keys/devices/ca.crt:/server_keys/ca.crt:ro
    ports:
      - 8443:8443
    depends_on:
      - treehub
      - tuf-reposerver
